title: Zsuark
email: krauszraphael@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My musings and experiments in Software Development, Computer Science and Mathematics.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zsuark.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: RaphaelKrausz
github_username:  Zsuark

# Build settings
markdown: kramdown
theme: jekyll-theme-architect
plugins:
  - jekyll-feed
  - jemoji

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

## RK further changes below

# 5 items per page
paginate: 5

# Default language is Australian English
lang: en-AU

# Google Analytics
google_analytics: UA-112330605-1

# Permalink style
permalink: pretty

# Github config
repository: Zsuark/zsuark.github.io

## NOTE: For youtube videos, look at this suggestion:
# http://www.adamwadeharris.com/how-to-easily-embed-youtube-videos-in-jekyll-sites-without-a-plugin/